# Generated by Django 4.2.4 on 2023-08-06 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('basic', models.CharField(default='', max_length=30)),
                ('ntur_allow', models.CharField(default='', max_length=30)),
                ('trnsport_allow', models.CharField(default='', max_length=30)),
                ('meal_allow', models.CharField(default='', max_length=30)),
                ('phone_allow', models.CharField(default='', max_length=30)),
                ('total', models.CharField(default='', max_length=30)),
                ('rwrd', models.CharField(default='', max_length=30)),
                ('rewrd_details', models.CharField(default='', max_length=100)),
                ('over_time', models.CharField(default='', max_length=30)),
                ('special_allow', models.CharField(default='', max_length=30)),
                ('special_details', models.CharField(default='', max_length=30)),
                ('total_attidtions', models.CharField(default='', max_length=30)),
                ('penalties', models.CharField(default='', max_length=30)),
                ('pnlts_details', models.CharField(default='', max_length=30)),
                ('absences', models.CharField(default='', max_length=30)),
                ('absences_Day', models.CharField(default='', max_length=30)),
                ('insurances', models.CharField(default='', max_length=30)),
                ('income_tax', models.CharField(default='', max_length=30)),
                ('medical_service', models.CharField(default='', max_length=30)),
                ('loans', models.CharField(default='', max_length=30)),
                ('deductions_hours', models.CharField(default='', max_length=30)),
                ('hours', models.CharField(default='', max_length=30)),
                ('car_deductions', models.CharField(default='', max_length=30)),
                ('another_deductions', models.CharField(default='', max_length=30)),
                ('total_deductions', models.CharField(default='', max_length=30)),
                ('net_salary', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
