# Generated by Django 4.2.4 on 2023-08-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Basic',
            new_name='اساسي',
        ),
    ]
