# Generated by Django 4.2.4 on 2023-08-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_basic_person_اساسي'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='اساسي',
            new_name='Basic',
        ),
    ]
