# Generated by Django 4.2.4 on 2023-08-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_absences_day_person_absences_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='detail_hours',
            field=models.CharField(default='', max_length=30),
        ),
    ]
